Like bare `await`, `for await` requires an `async` function since it yields the current execution context.

```ts
function test() {
  const a = [Promise.resolve(1), Promise.resolve(2)]
  for await (const x of a) {
    console.log(x)
  }
}
```

To fix the error, convert the enclosing function to an `async` function.

```ts
async function test() {
  const a = [Promise.resolve(1), Promise.resolve(2)]
  for await (const x of a) {
    console.log(x)
  }
}
```
